### ISSUE TITLE
Rise AxiosError 

### ISSUE THREAD

**Issue by tedyang-keda** [atomicals/atomicals-js#117]
"success": false,
  "message": "AxiosError: Request failed with status code 502",
  "error": {
    "message": "Request failed with status code 502",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 502\n    at settle (/Users/yangxuewen6/workSpace/git/atomicals-js1/node_modules/axios/dist/node/axios.cjs:1913:12)\n    at IncomingMessage.handleStreamEnd (/Users/yangxuewen6/workSpace/git/atomicals-js1/node_modules/axios/dist/node/axios.cjs:2995:11)\n    at IncomingMessage.emit (node:events:526:35)\n    at endReadableNT (node:internal/streams/readable:1589:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
    
    what that mean , how can i fix it ?

**Comment by AlexV525** [comment]
This is an issue related to the proxy server, make more retries and you'll get the result when the proxy becomes alive.
