### ISSUE TITLE
Cannot read properties of undefined (reading 'byteLength') with latest version

### ISSUE THREAD

**Issue by www222fff** [atomicals/atomicals-js#146]
Waiting for workers to complete...
got one finalCopyData:undefined
Solution found, try composing the transaction...
node:internal/event_target:777
  process.nextTick(() => { throw err; });
                           ^

TypeError: Cannot read properties of undefined (reading 'byteLength')
    at chunkBuffer (/home/dannyaw/blockchain/atomicals-js/dist/utils/file-utils.js:132:24)
    at appendMintUpdateRevealScript (/home/dannyaw/blockchain/atomicals-js/dist/commands/command-helpers.js:516:49)
    at prepareCommitRevealConfig (/home/dannyaw/blockchain/atomicals-js/dist/commands/command-helpers.js:142:67)
    at Worker.<anonymous> (/home/dannyaw/blockchain/atomicals-js/dist/utils/atomical-operation-builder.js:511:99)
    at Worker.emit (node:events:390:28)
    at MessagePort.<anonymous> (node:internal/worker:232:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by lanxinr** [comment]
same issues
