### ISSUE TITLE
Why returning error code 500 when operating mint-dft?

### ISSUE THREAD

**Issue by TTa77** [atomicals/atomicals-js#168]
When I was trying to run `yarn cli mint-dft quark --satsbyte 80`, the script exit with a 500 status code.

Here is the error message:
`AxiosError: Request failed with status code 500`
`    at settle (D:\atomicals\atomicals-js\node_modules\axios\dist\node\axios.cjs:1913:12)`
`    at IncomingMessage.handleStreamEnd (D:\atomicals\atomicals-js\node_modules\axios\dist\node\axios.cjs:2995:11)`
`    at IncomingMessage.emit (node:events:526:35)`
`    at endReadableNT (node:internal/streams/readable:1589:12)`
`    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)`

I am not good at JS and webserver, can anyone help me about this issue? Whether this is my own mistake or the server's problem?

**Comment by timecool-cpu** [comment]
i have the same problem

**Comment by TTa77** [comment]
> i have the same problem

Happened suddenly in this morning right? I run the script normally until about 11am

**Comment by haelking** [comment]
same happenned 3 hours ago

**Comment by starwound** [comment]
+1 on the issue, my script failed just now

**Comment by hezhaolei** [comment]
+1 
error": {
    "message": "Request failed with status code 500",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 500\n    at settle (D:\\BTC\\quark\\atomicals-js\\node_modules\\axios\\dist\\node\\axios.cjs:1913:12)\n    at IncomingMessa
ge.handleStreamEnd (D:\\BTC\\quark\\atomicals-js\\node_modules\\axios\\dist\\node\\axios.cjs:2995:11)\n    at IncomingMessage.emit (node:events:526:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",

**Comment by danbaise** [comment]
+1
failed, code 500

**Comment by 111Coin** [comment]
I have the same problem today.

**Comment by iCodyYang** [comment]
+1
failed, code 500

**Comment by feikerwu** [comment]
+1 
failed, code 500

**Comment by timecool-cpu** [comment]
hello everybody，i solve this problem!

open .env and replace 
https://ep.atomicals.xyz/proxy
to
https://ep.atomicalmarket.com/proxy

**Comment by haelking** [comment]
> hello everybody，i solve this problem!
> 
> open .env and replace https://ep.atomicals.xyz/proxy to https://ep.atomicalmarket.com/proxy

thanks bro

**Comment by 735946969** [comment]
> hello everybody，i solve this problem!
> 
> open .env and replace https://ep.atomicals.xyz/proxy to https://ep.atomicalmarket.com/proxy

Error: Decentralized mint for atom completely minted out! after change base url

**Comment by timecool-cpu** [comment]
> > hello everybody，i solve this problem!
> > open .env and replace https://ep.atomicals.xyz/proxy to https://ep.atomicalmarket.com/proxy
> 
> Error: Decentralized mint for atom completely minted out! after change base url

Let me take a look at the current file content.
many people work

**Comment by 735946969** [comment]
> > > hello everybody，i solve this problem!
> > > open .env and replace https://ep.atomicals.xyz/proxy to https://ep.atomicalmarket.com/proxy
> > 
> > 
> > Error: Decentralized mint for atom completely minted out! after change base url
> 
> Let me take a look at the current file content. many people work
![image](https://github.com/atomicals/atomicals-js/assets/33108886/fefd3752-5bc4-42f5-8ac5-e8bc614cef8f)

**Comment by timecool-cpu** [comment]
it is same with me,I donnot know where is the problem.
<img width="682" alt="image" src="https://github.com/atomicals/atomicals-js/assets/81469512/f8cfb782-61ca-4127-91bb-d2cea020693b">

**Comment by pan3da** [comment]
> > hello everybody，i solve this problem!
> > open .env and replace https://ep.atomicals.xyz/proxy to https://ep.atomicalmarket.com/proxy
> 
> Error: Decentralized mint for atom completely minted out! after change base url

The `atom` token is minted out. You should try some other tokens.
