### ISSUE TITLE
AxiosError: Request failed with status code 500

### ISSUE THREAD

**Issue by sanshao** [atomicals/atomicals-js#198]
Mint for ticker:  quark
AxiosError: Request failed with status code 500
    at settle (/Users/sanshao/workspace/github/atomicals-js/node_modules/axios/dist/node/axios.cjs:1913:12)
    at IncomingMessage.handleStreamEnd (/Users/sanshao/workspace/github/atomicals-js/node_modules/axios/dist/node/axios.cjs:2995:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1589:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {

`
{
  "success": false,
  "message": "AxiosError: Request failed with status code 500",
  "error": {
    "message": "Request failed with status code 500",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 500\n    at settle (/Users/sanshao/workspace/github/atomicals-js/node_modules/axios/dist/node/axios.cjs:1913:12)\n    at IncomingMessage.handleStreamEnd (/Users/sanshao/workspace/github/atomicals-js/node_modules/axios/dist/node/axios.cjs:2995:11)\n    at IncomingMessage.emit (node:events:526:35)\n    at endReadableNT (node:internal/streams/readable:1589:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
    "config": {
      "transitional": {
        "silentJSONParsing": true,
        "forcedJSONParsing": true,
        "clarifyTimeoutError": false
      },
      "adapter": [
        "xhr",
        "http"
      ],
      "transformRequest": [
        null
      ],
      "transformResponse": [
        null
      ],
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1,
      "maxBodyLength": -1,
      "env": {},
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Content-Type": "application/json",
        "User-Agent": "axios/1.5.1",
        "Content-Length": "81",
        "Accept-Encoding": "gzip, compress, deflate, br"
      },
      "method": "post",
`

**Comment by solofang** [comment]
也有类似问题。。。。502  BAD gateway

**Comment by Cortexico** [comment]
This is probably due to the electrumx proxy, that's why they recommend to run one. I tried with different ones and it kind of work sometimes, but I really think you need your own RPC server so you have no issues like this one.

**Comment by shiralwz** [comment]
@Cortexico  Could you please provide instructions on setting up the RPC server?
After paying the gas fee, I also encountered a 502 error.....

**Comment by a5520614000** [comment]
> This is probably due to the electrumx proxy, that's why they recommend to run one. I tried with different ones and it kind of work sometimes, but I really think you need your own RPC server so you have no issues like this one.

Currently, the terminal continues to encounter this error. However, the transfer has already been sent to the specified wallet. If the terminal is closed, will a refund be issued?

**Comment by soran989** [comment]
> @Cortexico Could you please provide instructions on setting up the RPC server? After paying the gas fee, I also encountered a 502 error.....

I would love to know that as well

**Comment by Cortexico** [comment]
You can find documentation here, everything is explained : 
https://github.com/atomicals/atomicals-electrumx
https://docs.atomicals.xyz/reference-and-tools/electrumx-api-and-public-endpoints
