### ISSUE TITLE
Why I can not mint-dft my ticker

### ISSUE THREAD

**Issue by agideo-code** [atomicals/atomicals-js#69]
npm run cli get-realm ab01
```
{
  "success": true,
  "data": {
    "global": {
      "coin": "Bitcoin",
      "network": "mainnet",
      "height": 818817,
      "block_tip": "0000000000000000000216ee0770fec493a57a57b03008b22c9261761ec7178c",
      "server_time": "2023-11-28T07:53:25.032488",
      "atomicals_block_tip": "ccc7bb1e7829a13ea65b711947d24cf409b7f4ebf8bfffe9814a6aec6acb710f",
      "atomical_count": 85804,
      "atomicals_block_hashes": {
        "818808": "dd76996c49228aeb9fb38eeceb0529e83b1afcee1e645e9f144edad1826a89a8",
        "818809": "54774d261c82bfae708fff6111b0ae6569f541a974e2493e8cad5c6e42569903",
        "818810": "32faec1df3a3ccde31185104b9f55a1046808f88bd2eadaff6aad4231fcdfa0d",
        "818811": "84ef174de2bc375e34362d2c03e2c3eda6f889fc1a19d515fa58bae038ab6e59",
        "818812": "ee6fa4818f895cce2fb6f0345612226d81dc91799b1cc1707bf61306012d5075",
        "818813": "8b9e9c895677a39fec68ec55e6625eca22a1110639824286894fa4b42df90d87",
        "818814": "5a5f4b827d15a2569ea716e432f1c7e882fd1b8ee8f725d3e73b4dbc6b36908e",
        "818815": "74e39fdfa61f399d89397617d14f036bf09882ed4334d61035506de843cb0506",
        "818816": "b8d2cf998f4e1878dbf740e5fb702ec3f618c080e7a36f7a6c16f3fb8e272aaa",
        "818817": "ccc7bb1e7829a13ea65b711947d24cf409b7f4ebf8bfffe9814a6aec6acb710f"
      }
    },
    "result": {
      "atomical_id": "3116bf07e63abf5df97e54e7351e0e6d671d1cef921b2e1861721e46d1a52c3ei0",
      "atomical_number": 85798,
      "atomical_ref": "64bby1z67aznvybyakkka7gednkht77fj8djw631e8f4dmd55gz0i0",
      "type": "NFT",
      "confirmed": true,
      "mint_info": {
        "commit_txid": "3116bf07e63abf5df97e54e7351e0e6d671d1cef921b2e1861721e46d1a52c3e",
        "commit_index": 0,
        "commit_location": "3116bf07e63abf5df97e54e7351e0e6d671d1cef921b2e1861721e46d1a52c3ei0",
        "commit_tx_num": 926881037,
        "commit_height": 818699,
        "reveal_location_txid": "5278bfc026119c9ee17d8ca345f4a53b3a7f04c605ce72871fccf2ea54ce5810",
        "reveal_location_index": 0,
        "reveal_location": "5278bfc026119c9ee17d8ca345f4a53b3a7f04c605ce72871fccf2ea54ce5810i0",
        "reveal_location_tx_num": 926881038,
        "reveal_location_height": 818699,
        "reveal_location_header": "00400a279e9e2e6e886ebd3936a69a7b889a5b4ac292b48782c80200000000000000000015142ac079edaf875d5064ae07828faa1abc71bfe9170fa9bce423556b3485cb158d6465502404171ae8d7d6",
        "reveal_location_blockhash": "a29bf117943b5a941313ffea90dfc35c8a49ee6e5c8002000000000000000000",
        "reveal_location_scripthash": "b344a2e69c82ff304ac571d901cdc89e36d8f6d13061c7b21da072b11faf5977",
        "reveal_location_script": "5120f1ff9344a265c6636c5d8dbcad5de3b9497602a5bb45f0ca7abfd3cb0e6a9c4e",
        "reveal_location_value": 1000,
        "args": {
          "time": 1701087436,
          "nonce": 8481472,
          "bitworkc": "3116",
          "request_realm": "ab01"
        },
        "meta": {},
        "ctx": {},
        "$request_realm": "ab01",
        "$immutable": false,
        "$bitwork": {
          "bitworkc": "3116",
          "bitworkr": null
        },
        "reveal_location_address": "bc1p78lex39zvhrxxmza3k726h0rh9yhvq49hdzlpjn6hlfukrn2n38q003eum",
        "blockheader_info": {
          "version": 654983168,
          "prevHash": "00000000000000000002c88287b492c24a5b9a887b9aa63639bd6e886e2e9e9e",
          "merkleRoot": "cb85346b5523e4bca90f17e9bf71bc1aaa8f8207ae64505d87afed79c02a1415",
          "timestamp": 1701088533,
          "bits": 386147408,
          "nonce": 3604473882
        }
      },
      "$bitwork": {
        "bitworkc": "3116",
        "bitworkr": null
      },
      "$realm_candidates": [
        {
          "tx_num": 926881037,
          "atomical_id": "3116bf07e63abf5df97e54e7351e0e6d671d1cef921b2e1861721e46d1a52c3ei0",
          "txid": "3116bf07e63abf5df97e54e7351e0e6d671d1cef921b2e1861721e46d1a52c3e",
          "commit_height": 818699,
          "reveal_location_height": 818699
        }
      ],
      "$request_realm_status": {
        "status": "verified",
        "verified_atomical_id": "3116bf07e63abf5df97e54e7351e0e6d671d1cef921b2e1861721e46d1a52c3ei0",
        "note": "Successfully verified and claimed realm for current Atomical"
      },
      "$request_realm": "ab01",
      "subtype": "realm",
      "$realm": "ab01",
      "$full_realm_name": "ab01",
      "mint_data": {
        "fields": {
          "args": {
            "time": 1701087436,
            "nonce": 8481472,
            "bitworkc": "3116",
            "request_realm": "ab01"
          }
        }
      }
    }
  }
}
```
npm run cli mint-dft ab01
```
> atomicals-js@0.1.46 cli
> node dist/cli.js mint-dft ab01

walletPath ./wallets/wallet.json
Args { mint_ticker: 'ab01' }
Meta undefined
Ctx undefined
====================================================================
Mint Interactive FT (Decentralized)
====================================================================
Atomical type: FUNGIBLE (decentralized) [
  {
    name: 'args',
    contentType: 'object',
    data: { mint_ticker: 'ab01' }
  }
] ab01
Mint for ticker:  ab01
error  AxiosError: Request failed with status code 500
    at settle (/root/apps/atomicals-js/node_modules/axios/dist/node/axios.cjs:1967:12)
    at IncomingMessage.handleStreamEnd (/root/apps/atomicals-js/node_modules/axios/dist/node/axios.cjs:3062:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_BAD_RESPONSE',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/1.6.2',
      'Content-Length': '17',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'post',
    url: 'https://ep.atomicals.xyz/proxy/blockchain.atomicals.get_ft_info',
    data: '{"params":[null]}'
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: true,
    _last: false,
    chunkedEncoding: false,
    shouldKeepAlive: true,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: '17',
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'ep.atomicals.xyz',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'ep.atomicals.xyz',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: null,
      _requestCert: true,
      _rejectUnauthorized: true,
      timeout: 5000,
      parser: null,
      _httpMessage: null,
      autoSelectFamilyAttemptedAddresses: [Array],
      handle: [TLSWrap],
      [Symbol(alpncallback)]: null,
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: -1,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 5000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 2196,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 62,
        [Symbol(triggerId)]: 60
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 1,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'POST /proxy/blockchain.atomicals.get_ft_info HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json\r\n' +
      'User-Agent: axios/1.6.2\r\n' +
      'Content-Length: 17\r\n' +
      'Accept-Encoding: gzip, compress, deflate, br\r\n' +
      'Host: ep.atomicals.xyz\r\n' +
      'Connection: keep-alive\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype] {},
      freeSockets: [Object: null prototype],
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/proxy/blockchain.atomicals.get_ft_info',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: null,
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 500,
      statusMessage: 'Internal Server Error',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://ep.atomicals.xyz/proxy/blockchain.atomicals.get_ft_info',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 36,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: true,
    host: 'ep.atomicals.xyz',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 17,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://ep.atomicals.xyz/proxy/blockchain.atomicals.get_ft_info',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'user-agent': [Array],
      'content-length': [Array],
      'accept-encoding': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kHighWaterMark)]: 16384,
    [Symbol(kRejectNonStandardBodyWrites)]: false,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 500,
    statusText: 'Internal Server Error',
    headers: Object [AxiosHeaders] {
      date: 'Tue, 28 Nov 2023 07:56:25 GMT',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '65',
      connection: 'keep-alive',
      'content-security-policy': "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests",
      'cross-origin-opener-policy': 'same-origin',
      'cross-origin-resource-policy': 'same-origin',
      'origin-agent-cluster': '?1',
      'referrer-policy': 'no-referrer',
      'strict-transport-security': 'max-age=15552000; includeSubDomains',
      'x-content-type-options': 'nosniff',
      'x-dns-prefetch-control': 'off',
      'x-download-options': 'noopen',
      'x-frame-options': 'SAMEORIGIN',
      'x-permitted-cross-domain-policies': 'none',
      'x-xss-protection': '0',
      'access-control-allow-origin': '*',
      etag: 'W/"41-yPkofH8EtcmRZ/tDmKHR7lRlToQ"'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      method: 'post',
      url: 'https://ep.atomicals.xyz/proxy/blockchain.atomicals.get_ft_info',
      data: '{"params":[null]}'
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '17',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: [TLSSocket],
      _header: 'POST /proxy/blockchain.atomicals.get_ft_info HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/1.6.2\r\n' +
        'Content-Length: 17\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: ep.atomicals.xyz\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/proxy/blockchain.atomicals.get_ft_info',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: true,
      host: 'ep.atomicals.xyz',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: { success: false, code: -32603, message: 'internal server error' }
  }
}
{
  "success": false,
  "message": "AxiosError: Request failed with status code 500",
  "error": {
    "message": "Request failed with status code 500",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 500\n    at settle (/root/apps/atomicals-js/node_modules/axios/dist/node/axios.cjs:1967:12)\n    at IncomingMessage.handleStreamEnd (/root/apps/atomicals-js/node_modules/axios/dist/node/axios.cjs:3062:11)\n    at IncomingMessage.emit (node:events:526:35)\n    at endReadableNT (node:internal/streams/readable:1408:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
    "config": {
      "transitional": {
        "silentJSONParsing": true,
        "forcedJSONParsing": true,
        "clarifyTimeoutError": false
      },
      "adapter": [
        "xhr",
        "http"
      ],
      "transformRequest": [
        null
      ],
      "transformResponse": [
        null
      ],
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1,
      "maxBodyLength": -1,
      "env": {},
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Content-Type": "application/json",
        "User-Agent": "axios/1.6.2",
        "Content-Length": "17",
        "Accept-Encoding": "gzip, compress, deflate, br"
      },
      "method": "post",
      "url": "https://ep.atomicals.xyz/proxy/blockchain.atomicals.get_ft_info",
      "data": "{\"params\":[null]}"
    },
    "code": "ERR_BAD_RESPONSE",
    "status": 500
  }
}
```

Did I miss any steps? Thanks

**Comment by AI-Chef** [comment]
try another rpc node

**Comment by agideo-code** [comment]
Thanks. but also error:

cat .env

```
ELECTRUMX_PROXY_BASE_URL=http://192.168.1.249:8080/proxy
WALLET_PATH=./wallets
WALLET_FILE=wallet.json
# testnet or livenet
NETWORK=livenet
ELECTRUMX_WSS=wss://192.168.1.249:50001
```

curl http://localhost:8080/proxy/health

```
{"success":true,"health":true}
```


npm run cli mint-dft ab01 --satsbyte 49

```

> atomicals-js@0.1.46 cli
> node dist/cli.js mint-dft ab01 49

walletPath ./wallets/wallet.json
Args { mint_ticker: 'ab01' }
Meta undefined
Ctx undefined
====================================================================
Mint Interactive FT (Decentralized)
====================================================================
Atomical type: FUNGIBLE (decentralized) [
  {
    name: 'args',
    contentType: 'object',
    data: { mint_ticker: 'ab01' }
  }
] ab01
Mint for ticker:  ab01
error  AxiosError: Request failed with status code 500
    at settle (/root/apps/atomicals-js/node_modules/axios/dist/node/axios.cjs:1967:12)
    at IncomingMessage.handleStreamEnd (/root/apps/atomicals-js/node_modules/axios/dist/node/axios.cjs:3062:11)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1408:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_BAD_RESPONSE',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/1.6.2',
      'Content-Length': '17',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'post',
    url: 'http://192.168.1.249:8080/proxy/blockchain.atomicals.get_ft_info',
    data: '{"params":[null]}'
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: true,
    _last: false,
    chunkedEncoding: false,
    shouldKeepAlive: true,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: '17',
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: true,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      timeout: 5000,
      parser: null,
      _httpMessage: null,
      [Symbol(async_id_symbol)]: -1,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 5000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 206,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 54,
        [Symbol(triggerId)]: 52
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: true,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 1,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _header: 'POST /proxy/blockchain.atomicals.get_ft_info HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json\r\n' +
      'User-Agent: axios/1.6.2\r\n' +
      'Content-Length: 17\r\n' +
      'Accept-Encoding: gzip, compress, deflate, br\r\n' +
      'Host: 192.168.1.249:8080\r\n' +
      'Connection: keep-alive\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype] {},
      freeSockets: [Object: null prototype],
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/proxy/blockchain.atomicals.get_ft_info',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: null,
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 500,
      statusMessage: 'Internal Server Error',
      client: [Socket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'http://192.168.1.249:8080/proxy/blockchain.atomicals.get_ft_info',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 38,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: true,
    host: '192.168.1.249',
    protocol: 'http:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 17,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'http://192.168.1.249:8080/proxy/blockchain.atomicals.get_ft_info',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'user-agent': [Array],
      'content-length': [Array],
      'accept-encoding': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kHighWaterMark)]: 16384,
    [Symbol(kRejectNonStandardBodyWrites)]: false,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 500,
    statusText: 'Internal Server Error',
    headers: Object [AxiosHeaders] {
      'content-security-policy': "default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests",
      'cross-origin-opener-policy': 'same-origin',
      'cross-origin-resource-policy': 'same-origin',
      'origin-agent-cluster': '?1',
      'referrer-policy': 'no-referrer',
      'strict-transport-security': 'max-age=15552000; includeSubDomains',
      'x-content-type-options': 'nosniff',
      'x-dns-prefetch-control': 'off',
      'x-download-options': 'noopen',
      'x-frame-options': 'SAMEORIGIN',
      'x-permitted-cross-domain-policies': 'none',
      'x-xss-protection': '0',
      'access-control-allow-origin': '*',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '65',
      etag: 'W/"41-yPkofH8EtcmRZ/tDmKHR7lRlToQ"',
      date: 'Tue, 28 Nov 2023 10:02:35 GMT',
      connection: 'keep-alive',
      'keep-alive': 'timeout=5'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      method: 'post',
      url: 'http://192.168.1.249:8080/proxy/blockchain.atomicals.get_ft_info',
      data: '{"params":[null]}'
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '17',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: [Socket],
      _header: 'POST /proxy/blockchain.atomicals.get_ft_info HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/1.6.2\r\n' +
        'Content-Length: 17\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: 192.168.1.249:8080\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/proxy/blockchain.atomicals.get_ft_info',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: true,
      host: '192.168.1.249',
      protocol: 'http:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: { success: false, code: -32603, message: 'internal server error' }
  }
}
{
  "success": false,
  "message": "AxiosError: Request failed with status code 500",
  "error": {
    "message": "Request failed with status code 500",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 500\n    at settle (/root/apps/atomicals-js/node_modules/axios/dist/node/axios.cjs:1967:12)\n    at IncomingMessage.handleStreamEnd (/root/apps/atomicals-js/node_modules/axios/dist/node/axios.cjs:3062:11)\n    at IncomingMessage.emit (node:events:526:35)\n    at endReadableNT (node:internal/streams/readable:1408:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
    "config": {
      "transitional": {
        "silentJSONParsing": true,
        "forcedJSONParsing": true,
        "clarifyTimeoutError": false
      },
      "adapter": [
        "xhr",
        "http"
      ],
      "transformRequest": [
        null
      ],
      "transformResponse": [
        null
      ],
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1,
      "maxBodyLength": -1,
      "env": {},
      "headers": {
        "Accept": "application/json, text/plain, */*",
        "Content-Type": "application/json",
        "User-Agent": "axios/1.6.2",
        "Content-Length": "17",
        "Accept-Encoding": "gzip, compress, deflate, br"
      },
      "method": "post",
      "url": "http://192.168.1.249:8080/proxy/blockchain.atomicals.get_ft_info",
      "data": "{\"params\":[null]}"
    },
    "code": "ERR_BAD_RESPONSE",
    "status": 500
  }
}
```

**Comment by agideo-code** [comment]
Any idea? Thanks

<img width="1260" alt="image" src="https://github.com/atomicals/atomicals-js/assets/37390606/f7d584a8-1470-44df-96d4-4a6061a665f9">

**Comment by agideo-code** [comment]
No, #60  is wallet setting error.
